@startuml

class Person {
  fornavn: String
  mellemnavn: String
  efternavn: String
  personnummer: Int

}
class Adresse {
  vejnavn: String
  nummer: Integer
  dørEllerSide: String
  postnummer: Integer

}
class OrgPerson {
  orgPersonNavn: String

}
class Organisation {
  organisationsnavn: String

}
class University {
  universityName String

}
Person o-- OrgPerson
Organisation o-- OrgPerson
Adresse --> University
University --> Organisation
@enduml